package model.Enum;

public enum Origin{
    CONNEXE_VIEW_BTN,
    PROCEDURE_VIEW_BTN,
    EDITOR_VIEW_BTN,
    ALL_AFF_DETAILS_VIEW_BTN,
    DISPACTH_BTN,
    REMOVE_EDITOR_FROM_LIST_BTN,
    PRINCIPAL_AFFAIRE_VIEW_DETAILS_BTN,
    USER_DETAILS_LOCK_BTN,
    DELETE_USER,
    SHOW_USER_PANEL,
    SHOW_AFFAIR_DETAILS,
    SHOW_ALL_AFFAIR_TRAITED_BY_EDITOR,
    DELETE_AFFAIR,
    CREATE_TITLE,
    REJETER_AFFAIRE,
    DELETE_TITLE,
    EDIT_TITLE,
    NEW_PROCEDURE,
    SHOW_AFFAIRE_DETAILS_FROM_EX_AFFAIRE,
    VALIDATE_ATTACHEMENT
}
