package model.Enum;

public enum TypeMutation{
    VENTE_DEFINITIVE,VENTE_SIMPLE,VENTE_SCR,DECE,PARTAGE,DONATION,DOTATION,DISPOSITION_GRATUITE,ECHANGE,JUGEMENT,CLASSEMENT,DECLASSEMENT,TRANSFERT,AUTRE
}
